cache: false
downloader: Curl
gpg-setting: GPGNone
keep-dirs: Errors
key-bindings:
  changelog:
    Key:
      KChar: c
    Mods: []
  down:
    Key:
      KChar: j
    Mods: []
  install:
    Key:
      KChar: i
    Mods: []
  quit:
    Key:
      KChar: q
    Mods: []
  set:
    Key:
      KChar: s
    Mods: []
  show-all:
    Key:
      KChar: a
    Mods: []
  show-all-tools:
    Key:
      KChar: t
    Mods: []
  uninstall:
    Key:
      KChar: u
    Mods: []
  up:
    Key:
      KChar: k
    Mods: []
meta-cache: null
meta-mode: null
mirrors: null
no-network: false
no-verify: false
platform-override: null
url-source:
- GHCupURL
verbose: false
